name: Releases

on: [push]

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            assset: EpJSON_Transition_Ubuntu2004
          - os: ubuntu-18.04
            assset: EpJSON_Transition_Ubuntu1804
          - os: macos-10.15
            assset: EpJSON_Transition_Mac1015
          - os: windows-2019
            assset: EpJSON_Transition_Windows

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Pip Dependencies
      shell: bash
      run: pip install pyinstaller

    - name: Build
      shell: bash
      run: pyinstaller --onefile epjson_transition.spec

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: EpJSON_Transition-${{ matrix.os }}
        path: dist/EpJSON_Transition*

    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/EpJSON_Transition*
        asset_name: ${{ matrix.asset }}
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true