name: Test
on: [push]
jobs:
  unit_test:
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
          - os: ubuntu-20.04
          - os: macos-10.15
          - os: windows-2019
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install -r requirements.txt
      - run: coverage run setup.py test
      - run: coverage report
      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github
